import { Vue } from "vue-property-decorator";
export default class Pagination extends Vue {
    pageSize: number;
    current: number;
    total: number;
    change: Function;
    pageSizeChange: Function;
    size: string;
    simple: boolean;
    layout: string;
    sizeOptions: number[];
    align: string;
    interCurrent: number;
    interPageSize: number;
    totalPage: number;
    get sizeClass(): "" | "is-small";
    get alignClass(): string;
    calcTotalPage(total: number, interPageSize: number): number;
    handleChangePage(p: any): void;
    handleJumpPrev(): void;
    handleJumpNext(): void;
    hasPrev(): boolean;
    hasNext(): boolean;
    handlePrev(): void;
    handleNext(): void;
    handleQuickJumper(e: any): void;
    handlePageSizeChange(e: any): void;
    onCurrentChange(val: number): void;
    onPageSizeChange(val: number): void;
    mounted(): void;
    render(h: any): import("vue").VNode;
}
